import { Analytics } from '@/components/analytics'
import '@/styles/globals.css'
import { cn } from '@/lib/utils'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: "/favicon.ico",
    // shortcut: "/favicon-16x16.png",
    // apple: "/apple-touch-icon.png",
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn(
      "font-sans text-slate-900 antialiased",
      fontSans.variable
    )} suppressHydrationWarning>
      <body className='bg-base min-h-full'>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
      </ThemeProvider>
      <Analytics />
      </body>
    </html>
  )
}
